---
- name: Install system packages
  ansible.builtin.apt:
    pkg:
      - python3.9
      - python3.9-dev
      - python3-pip
      - rsync

- name: Checkout source code
  ansible.builtin.include_role:
    name: mila.clockwork
    tasks_from: checkout_src

- name: Install slurm_state requirements with pip
  ansible.builtin.pip:
    requirements: "{{ clockwork_install_path }}/scripts/requirements.txt"

- name: Create clockwork user
  ansible.builtin.include_role:
    name: mila.clockwork
    tasks_from: create_user

- name: Setup user update scripts
  ansible.builtin.template:
    src: templates/clockwork-users.service.j2
    dest: /etc/systemd/system/clockwork-users.service
    mode: 0600

- name: Setup system timer trigger
  ansible.builtin.template:
    src: templates/clockwork-users.timer.j2
    dest: /etc/systemd/system/clockwork-users.timer
    mode: 0600

- name: Ensure config dir is present
  ansible.builtin.file:
    path: /etc/clockwork
    mode: 0700
    state: directory
    owner: "{{ clockwork_user }}"

- name: Install ldap private key
  ansible.builtin.file:
    content: "{{ clockwork_ldap_private_key }}"
    dest: /etc/clockwork/clockwork_ldap.key
    mode: 0600
    owner: "{{ clockwork_user }}"

- name: Install ldap certificate
  ansible.builtin.file:
    content: "{{ clockwork_ldap_certificate }}"
    dest: /etc/clockwork/clockwork_ldap.crt
    mode: 0600
    owner: "{{ clockwork_user }}"

- name: Enable systemd timers
  ansible.builtin.systemd:
    daemon-reload: yes
    enabled: true
    state: started
    name: clockwork-users.timer
