- name: Checkout source code
  ansible.builtin.include_role:
    name: mila.clockwork
    tasks_from: checkout_src

- name: Ensure the Cluster Stats Cache script is executable
  ansible.builtin.file:
    path: "{{ clockwork_install_path }}/slurm_state/cron_scripts/generate_clusterstats_cache.sh"
    mode: '0755'

- name: Configure path to Slurm commands in cron
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: "/opt/slurm/bin:/usr/bin:/bin"
    user: "{{ clockwork_clusterstats_cron_user | default(clockwork_user) }}"

- name: Configure cron to execute Cluster Stats Cache script
  ansible.builtin.cron:
    name: "Generate Cluster Stats Cache"
    job: "{{ clockwork_install_path }}/slurm_state/cron_scripts/generate_clusterstats_cache.sh"
    minute: "{{ clockwork_clusterstats_cron_minute }}"
    user: "{{ clockwork_clusterstats_cron_user | default(clockwork_user) }}"
