---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_systemd
    image: debian11_systemd
    dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
